"""Multilingual entity names for all curated sensors (by translation_key).

Keyed by translation_key. English values match curated.name in data.py.
Regenerate coverage check: python tools/verify_sensor_translations.py
"""

from __future__ import annotations

# en -> {de, fr, it, nl} — reused when several sensors share the same English name
_BY_ENGLISH: dict[str, dict[str, str]] = {
    "Battery": {
        "de": "Batterie",
        "fr": "Batterie",
        "it": "Batteria",
        "nl": "Accu",
    },
    "Target charge level": {
        "de": "Ladeziel",
        "fr": "Niveau de charge cible",
        "it": "Livello di carica target",
        "nl": "Laaddoel",
    },
    "Charge bulk threshold": {
        "de": "Bulk-Ladeschwelle",
        "fr": "Seuil de charge bulk",
        "it": "Soglia carica bulk",
        "nl": "Bulk-laaddrempel",
    },
    "Charge power": {
        "de": "Ladeleistung",
        "fr": "Puissance de charge",
        "it": "Potenza di carica",
        "nl": "Laadvermogen",
    },
    "Charge rate": {
        "de": "Laderate",
        "fr": "Vitesse de charge",
        "it": "Velocità di carica",
        "nl": "Laadsnelheid",
    },
    "Charged energy": {
        "de": "Geladene Energie",
        "fr": "Énergie chargée",
        "it": "Energia caricata",
        "nl": "Geladen energie",
    },
    "Remaining charging time": {
        "de": "Restladedauer",
        "fr": "Temps de charge restant",
        "it": "Tempo di carica rimanente",
        "nl": "Resterende laadtijd",
    },
    "Remaining time to bulk": {
        "de": "Restzeit bis Bulk",
        "fr": "Temps restant jusqu'au bulk",
        "it": "Tempo rimanente al bulk",
        "nl": "Resterende tijd tot bulk",
    },
    "Battery energy": {
        "de": "Batterieenergie",
        "fr": "Énergie batterie",
        "it": "Energia batteria",
        "nl": "Accu-energie",
    },
    "Battery capacity": {
        "de": "Batteriekapazität",
        "fr": "Capacité batterie",
        "it": "Capacità batteria",
        "nl": "Accucapaciteit",
    },
    "HV battery level": {
        "de": "HV-Batteriestand",
        "fr": "Niveau batterie HV",
        "it": "Livello batteria HV",
        "nl": "HV-accuniveau",
    },
    "BCAM charge threshold": {
        "de": "BCAM-Ladeschwelle",
        "fr": "Seuil de charge BCAM",
        "it": "Soglia carica BCAM",
        "nl": "BCAM-laaddrempel",
    },
    "Charging error code": {
        "de": "Ladefehlercode",
        "fr": "Code erreur charge",
        "it": "Codice errore carica",
        "nl": "Laadfoutcode",
    },
    "Mileage": {
        "de": "Kilometerstand",
        "fr": "Kilométrage",
        "it": "Chilometraggio",
        "nl": "Kilometerstand",
    },
    "Electric range": {
        "de": "Elektrische Reichweite",
        "fr": "Autonomie électrique",
        "it": "Autonomia elettrica",
        "nl": "Elektrisch bereik",
    },
    "Remaining climate time": {
        "de": "Rest-Klimazeit",
        "fr": "Temps clim restant",
        "it": "Tempo clima rimanente",
        "nl": "Resterende klimaattijd",
    },
    "Residual energy": {
        "de": "Restenergie",
        "fr": "Énergie résiduelle",
        "it": "Energia residua",
        "nl": "Restenergie",
    },
    "Residual consumption": {
        "de": "Restverbrauch",
        "fr": "Consommation résiduelle",
        "it": "Consumo residuo",
        "nl": "Restverbruik",
    },
    "Climate consumption": {
        "de": "Klimaverbrauch",
        "fr": "Consommation climatisation",
        "it": "Consumo clima",
        "nl": "Klimaatverbruik",
    },
    "Uphill consumption": {
        "de": "Verbrauch bergauf",
        "fr": "Consommation montée",
        "it": "Consumo in salita",
        "nl": "Verbruik bergop",
    },
    "Downhill consumption": {
        "de": "Verbrauch bergab",
        "fr": "Consommation descente",
        "it": "Consumo in discesa",
        "nl": "Verbruik bergaf",
    },
    "Outside temperature": {
        "de": "Außentemperatur",
        "fr": "Température extérieure",
        "it": "Temperatura esterna",
        "nl": "Buitentemperatuur",
    },
    "Battery min temperature": {
        "de": "Batterie Min-Temperatur",
        "fr": "Temp. min batterie",
        "it": "Temp. min batteria",
        "nl": "Accu min-temperatuur",
    },
    "Battery max temperature": {
        "de": "Batterie Max-Temperatur",
        "fr": "Temp. max batterie",
        "it": "Temp. max batteria",
        "nl": "Accu max-temperatuur",
    },
    "Last connected": {
        "de": "Zuletzt verbunden",
        "fr": "Dernière connexion",
        "it": "Ultima connessione",
        "nl": "Laatst verbonden",
    },
    "Last vehicle update": {
        "de": "Letztes Fahrzeug-Update",
        "fr": "Dernière mise à jour véhicule",
        "it": "Ultimo aggiornamento veicolo",
        "nl": "Laatste voertuigupdate",
    },
    "Dataset generated": {
        "de": "Datensatz erzeugt",
        "fr": "Jeu de données généré",
        "it": "Dataset generato",
        "nl": "Dataset gegenereerd",
    },
    "Last telemetry": {
        "de": "Letzte Telemetrie",
        "fr": "Dernière télémétrie",
        "it": "Ultima telemetria",
        "nl": "Laatste telemetrie",
    },
    "Vehicle clock": {
        "de": "Fahrzeuguhr",
        "fr": "Horloge véhicule",
        "it": "Orologio veicolo",
        "nl": "Voertuigklok",
    },
    "BEM level": {
        "de": "BEM-Level",
        "fr": "Niveau BEM",
        "it": "Livello BEM",
        "nl": "BEM-niveau",
    },
    "Range (combined)": {
        "de": "Reichweite (kombiniert)",
        "fr": "Autonomie (combinée)",
        "it": "Autonomia (combinata)",
        "nl": "Bereik (gecombineerd)",
    },
    "Range (primary)": {
        "de": "Reichweite (primär)",
        "fr": "Autonomie (principale)",
        "it": "Autonomia (primaria)",
        "nl": "Bereik (primair)",
    },
    "Range (secondary)": {
        "de": "Reichweite (sekundär)",
        "fr": "Autonomie (secondaire)",
        "it": "Autonomia (secondaria)",
        "nl": "Bereik (secundair)",
    },
    "SCR range": {
        "de": "SCR-Reichweite",
        "fr": "Autonomie SCR",
        "it": "Autonomia SCR",
        "nl": "SCR-bereik",
    },
    "Total energy charged": {
        "de": "Gesamt geladene Energie",
        "fr": "Énergie totale chargée",
        "it": "Energia totale caricata",
        "nl": "Totaal geladen energie",
    },
    "Fuel level": {
        "de": "Tankfüllstand",
        "fr": "Niveau de carburant",
        "it": "Livello carburante",
        "nl": "Brandstofniveau",
    },
    "Fuel level accuracy": {
        "de": "Tankfüllstand-Genauigkeit",
        "fr": "Précision niveau carburant",
        "it": "Precisione livello carburante",
        "nl": "Brandstofniveau-nauwkeurigheid",
    },
    "CNG gas level": {
        "de": "CNG-Gasfüllstand",
        "fr": "Niveau gaz CNG",
        "it": "Livello gas CNG",
        "nl": "CNG-gasniveau",
    },
    "Tire pressure FL": {
        "de": "Reifendruck VL",
        "fr": "Pression pneu AVG",
        "it": "Pressione gomma ASX",
        "nl": "Bandenspanning LV",
    },
    "Tire pressure FR": {
        "de": "Reifendruck VR",
        "fr": "Pression pneu AVD",
        "it": "Pressione gomma ADX",
        "nl": "Bandenspanning RV",
    },
    "Tire pressure RL": {
        "de": "Reifendruck HL",
        "fr": "Pression pneu ARG",
        "it": "Pressione gomma PSX",
        "nl": "Bandenspanning LA",
    },
    "Tire pressure RR": {
        "de": "Reifendruck HR",
        "fr": "Pression pneu ARD",
        "it": "Pressione gomma PDX",
        "nl": "Bandenspanning RA",
    },
    "Tire pressure spare": {
        "de": "Reifendruck Ersatz",
        "fr": "Pression pneu secours",
        "it": "Pressione gomma scorta",
        "nl": "Bandenspanning reserve",
    },
    "Tire pressure diff FL": {
        "de": "Reifendruck-Diff. VL",
        "fr": "Écart pression AVG",
        "it": "Diff. pressione ASX",
        "nl": "Spanningverschil LV",
    },
    "Tire pressure diff FR": {
        "de": "Reifendruck-Diff. VR",
        "fr": "Écart pression AVD",
        "it": "Diff. pressione ADX",
        "nl": "Spanningverschil RV",
    },
    "Tire pressure diff RL": {
        "de": "Reifendruck-Diff. HL",
        "fr": "Écart pression ARG",
        "it": "Diff. pressione PSX",
        "nl": "Spanningverschil LA",
    },
    "Tire pressure diff RR": {
        "de": "Reifendruck-Diff. HR",
        "fr": "Écart pression ARD",
        "it": "Diff. pressione PDX",
        "nl": "Spanningverschil RA",
    },
    "Tire pressure diff spare": {
        "de": "Reifendruck-Diff. Ersatz",
        "fr": "Écart pression secours",
        "it": "Diff. pressione scorta",
        "nl": "Spanningverschil reserve",
    },
    "Front left window position": {
        "de": "Fensterposition VL",
        "fr": "Position vitre AVG",
        "it": "Posizione finestrino ASX",
        "nl": "Raampositie LV",
    },
    "Front right window position": {
        "de": "Fensterposition VR",
        "fr": "Position vitre AVD",
        "it": "Posizione finestrino ADX",
        "nl": "Raampositie RV",
    },
    "Rear left window position": {
        "de": "Fensterposition HL",
        "fr": "Position vitre ARG",
        "it": "Posizione finestrino PSX",
        "nl": "Raampositie LA",
    },
    "Rear right window position": {
        "de": "Fensterposition HR",
        "fr": "Position vitre ARD",
        "it": "Posizione finestrino PDX",
        "nl": "Raampositie RA",
    },
    "Sunroof position": {
        "de": "Schiebedachposition",
        "fr": "Position toit ouvrant",
        "it": "Posizione tetto apribile",
        "nl": "Schuifdakpositie",
    },
    "Inspection interval": {
        "de": "Inspektionsintervall",
        "fr": "Intervalle inspection",
        "it": "Intervallo ispezione",
        "nl": "Inspectie-interval",
    },
    "Oil change interval": {
        "de": "Ölwechsel-Intervall",
        "fr": "Intervalle vidange",
        "it": "Intervallo cambio olio",
        "nl": "Oliebeurt-interval",
    },
    "Inspection distance": {
        "de": "Inspektion (Strecke)",
        "fr": "Distance inspection",
        "it": "Distanza ispezione",
        "nl": "Inspectie (afstand)",
    },
    "Oil change distance": {
        "de": "Ölwechsel (Strecke)",
        "fr": "Distance vidange",
        "it": "Distanza cambio olio",
        "nl": "Oliebeurt (afstand)",
    },
    "Trip distance (long)": {
        "de": "Strecke (Langzeit)",
        "fr": "Distance trajet (long)",
        "it": "Distanza viaggio (lungo)",
        "nl": "Afstand rit (lang)",
    },
    "Trip start mileage (long)": {
        "de": "Start-km (Langzeit)",
        "fr": "Km départ (long)",
        "it": "Km partenza (lungo)",
        "nl": "Start-km (lang)",
    },
    "Avg fuel consumption (long)": {
        "de": "Ø Verbrauch Benzin (Langzeit)",
        "fr": "Conso. moy. essence (long)",
        "it": "Consumo medio benzina (lungo)",
        "nl": "Gem. verbruik benzine (lang)",
    },
    "Avg electric consumption (long)": {
        "de": "Ø Verbrauch Strom (Langzeit)",
        "fr": "Conso. moy. élec. (long)",
        "it": "Consumo medio elettrico (lungo)",
        "nl": "Gem. verbruik stroom (lang)",
    },
    "Avg speed (long)": {
        "de": "Ø Geschwindigkeit (Langzeit)",
        "fr": "Vitesse moy. (long)",
        "it": "Velocità media (lungo)",
        "nl": "Gem. snelheid (lang)",
    },
    "Travel time (long)": {
        "de": "Fahrzeit (Langzeit)",
        "fr": "Temps trajet (long)",
        "it": "Tempo di viaggio (lungo)",
        "nl": "Rijtijd (lang)",
    },
    "Trip distance (short)": {
        "de": "Strecke (Kurzzeit)",
        "fr": "Distance trajet (court)",
        "it": "Distanza viaggio (breve)",
        "nl": "Afstand rit (kort)",
    },
    "Trip start mileage (short)": {
        "de": "Start-km (Kurzzeit)",
        "fr": "Km départ (court)",
        "it": "Km partenza (breve)",
        "nl": "Start-km (kort)",
    },
    "Avg fuel consumption (short)": {
        "de": "Ø Verbrauch Benzin (Kurzzeit)",
        "fr": "Conso. moy. essence (court)",
        "it": "Consumo medio benzina (breve)",
        "nl": "Gem. verbruik benzine (kort)",
    },
    "Avg electric consumption (short)": {
        "de": "Ø Verbrauch Strom (Kurzzeit)",
        "fr": "Conso. moy. élec. (court)",
        "it": "Consumo medio elettrico (breve)",
        "nl": "Gem. verbruik stroom (kort)",
    },
    "Travel time (short)": {
        "de": "Fahrzeit (Kurzzeit)",
        "fr": "Temps trajet (court)",
        "it": "Tempo di viaggio (breve)",
        "nl": "Rijtijd (kort)",
    },
    "Oil level": {
        "de": "Ölstand",
        "fr": "Niveau d'huile",
        "it": "Livello olio",
        "nl": "Oliepeil",
    },
    "Additional oil level": {
        "de": "Zusatz-Ölstand",
        "fr": "Niveau huile additionnel",
        "it": "Livello olio aggiuntivo",
        "nl": "Extra oliepeil",
    },
    "Max oil level": {
        "de": "Max. Ölstand",
        "fr": "Niveau huile max",
        "it": "Livello olio max",
        "nl": "Max. oliepeil",
    },
    "Oil dipstick indicator": {
        "de": "Ölmessstab-Anzeige",
        "fr": "Indicateur jauge huile",
        "it": "Indicatore asta olio",
        "nl": "Oliemeter-indicator",
    },
    "Last charge": {
        "de": "Letzte Ladung",
        "fr": "Dernière charge",
        "it": "Ultima carica",
        "nl": "Laatste lading",
    },
    "Days until subscription expires": {
        "de": "Tage bis Abo endet",
        "fr": "Jours avant expiration de l'abonnement",
        "it": "Giorni alla scadenza abbonamento",
        "nl": "Dagen tot abonnement verloopt",
    },
    "Minutes since last snapshot": {
        "de": "Minuten seit letztem Snapshot",
        "fr": "Minutes depuis le dernier instantané",
        "it": "Minuti dall'ultimo snapshot",
        "nl": "Minuten sinds laatste snapshot",
    },
    "Uncurated fields": {
        "de": "Nicht kuratierte Felder",
        "fr": "Champs non traités",
        "it": "Campi non curati",
        "nl": "Niet-gecureerde velden",
    },
}

# translation_key -> English name (all curated sensors)
_SENSOR_KEYS: dict[str, str] = {
    "battery_state_report_soc": "Battery",
    "hv_battery_level": "HV battery level",
    "settings_target_soc": "Target charge level",
    "battery_state_report_charge_bulk_threshold": "Charge bulk threshold",
    "battery_state_report_charge_power": "Charge power",
    "battery_state_report_charge_rate": "Charge rate",
    "battery_state_report_charge_energy": "Charged energy",
    "battery_state_report_remaining_charging_time_complete": "Remaining charging time",
    "battery_state_report_remaining_charging_time_bulk": "Remaining time to bulk",
    "energy_contents_current_energy_content_physical_value": "Battery energy",
    "energy_contents_maximal_energy_content_physical_value": "Battery capacity",
    "battery_care_mode_charge_bcam_threshold": "BCAM charge threshold",
    "charging_state_report_error_code": "Charging error code",
    "mileage_value": "Mileage",
    "range_value": "Electric range",
    "value_of_the_primary_range": "Electric range",
    "remaining_climate_time": "Remaining climate time",
    "residual_energy_in_percent": "Residual energy",
    "additional_consumptions_residual_consumption": "Residual consumption",
    "additional_consumptions_interior_climatization_consumption": "Climate consumption",
    "slope_consumption_values_ascent_slope_consumption_physical_value": "Uphill consumption",
    "slope_consumption_values_descent_slope_consumption_physical_value": "Downhill consumption",
    "outdoor_temperature": "Outside temperature",
    "min_temperature": "Battery min temperature",
    "max_temperature": "Battery max temperature",
    "mileage_value_timestamp": "Last connected",
    "car_captured_time": "Last telemetry",
    "instrument_cluster_time": "Vehicle clock",
    "bem_level": "BEM level",
    "mileage": "Mileage",
    "cruising_range_combined": "Range (combined)",
    "cruising_range_primary_engine": "Range (primary)",
    "cruising_range_secondary_engine": "Range (secondary)",
    "range": "Electric range",
    "scr_range": "SCR range",
    "state_of_charge": "Battery",
    "remaining_charging_time": "Remaining charging time",
    "charged_energy": "Total energy charged",
    "fuel_level_current_level": "Fuel level",
    "fuel_level__accuracy": "Fuel level accuracy",
    "cng_gas_level": "CNG gas level",
    "outside_temperature": "Outside temperature",
    "tyre_pressure_actual_front_left": "Tire pressure FL",
    "tyre_pressure_actual_front_right": "Tire pressure FR",
    "tyre_pressure_actual_rear_left": "Tire pressure RL",
    "tyre_pressure_actual_rear_right": "Tire pressure RR",
    "tyre_pressure_actual_spare_tyre": "Tire pressure spare",
    "tyre_pressure_differential_front_left": "Tire pressure diff FL",
    "tyre_pressure_differential_front_right": "Tire pressure diff FR",
    "tyre_pressure_differential_rear_left": "Tire pressure diff RL",
    "tyre_pressure_differential_rear_right": "Tire pressure diff RR",
    "tyre_pressure_differential_spare_tyre": "Tire pressure diff spare",
    "position_front_left_door_window_lifter": "Front left window position",
    "position_front_right_door_window_lifter": "Front right window position",
    "position_rear_left_door_window_lifter": "Rear left window position",
    "position_rear_right_door_window_lifter": "Rear right window position",
    "position_sunroof_motor_hood_1": "Sunroof position",
    "maintenance_interval__time_until_inspection": "Inspection interval",
    "maintenance_interval__time_until_oil_change": "Oil change interval",
    "maintenance_interval_distance_until_inspection": "Inspection distance",
    "maintenance_interval_distance_until_oil_change": "Oil change distance",
    "long_term_data_mileage": "Trip distance (long)",
    "long_term_data_start_mileage": "Trip start mileage (long)",
    "long_term_data_average_fuel_consumption": "Avg fuel consumption (long)",
    "long_term_data_average_electr_engine_consumption": "Avg electric consumption (long)",
    "long_term_data_average_speed": "Avg speed (long)",
    "long_term_data_travel_time": "Travel time (long)",
    "short_term_data_mileage": "Trip distance (short)",
    "short_term_data_start_mileage": "Trip start mileage (short)",
    "short_term_data_average_fuel_consumption": "Avg fuel consumption (short)",
    "short_term_data_average_electr_engine_consumption": "Avg electric consumption (short)",
    "short_term_data_travel_time": "Travel time (short)",
    "oil_level_actual_level": "Oil level",
    "oil_level_additional_oil_level": "Additional oil level",
    "oil_level_total_max": "Max oil level",
    "oil_level_dipstick_indicator_function": "Oil dipstick indicator",
    "mileage_timestamp": "Last connected",
    "last_charge_kwh": "Last charge",
    "last_connected": "Last connected",
    "last_vehicle_update": "Last vehicle update",
    "dataset_generated": "Dataset generated",
    "days_until_subscription_expires": "Days until subscription expires",
    "minutes_since_last_snapshot": "Minutes since last snapshot",
    "uncurated_fields_count": "Uncurated fields",
}


def _labels(en: str) -> dict[str, str]:
    loc = _BY_ENGLISH[en]
    return {"en": en, **loc}


def build_name_labels() -> dict[str, dict]:
    """Return {translation_key: {names: {lang: label}}} for measurement sensors."""
    out: dict[str, dict] = {}
    for key, en in _SENSOR_KEYS.items():
        out[key] = {"names": _labels(en)}
    return out


NAME_LABELS: dict[str, dict] = build_name_labels()
